"""add_asin_to_products

Revision ID: 03369edf48f9
Revises: 343c621d0d01
Create Date: 2026-05-12 10:24:27.369451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03369edf48f9'
down_revision: Union[str, None] = '343c621d0d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('asin', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'asin')
    # ### end Alembic commands ###
