"""initial_schema

Revision ID: 945da85cfa2d
Revises: 
Create Date: 2026-05-11 17:56:59.600783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945da85cfa2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('msrp_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_file_name', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_text_path', sa.String(length=500), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=True),
    sa.Column('hashtag_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('engagement_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('creator_post_count', sa.Integer(), nullable=False),
    sa.Column('viral_threshold_hit', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vibe_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('score_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vibe_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_band', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_value', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('baseline_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_source_summary', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vibe_score_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weighted_contribution', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feature_count', sa.String(length=10), nullable=True),
    sa.Column('top_signals', sa.JSON(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('evidence_texts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vibe_score_id'], ['vibe_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviewer_type', sa.String(length=50), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('ingestion_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shap_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vibe_score_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=200), nullable=False),
    sa.Column('shap_value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('feature_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('feature_value_raw', sa.String(length=500), nullable=True),
    sa.Column('rank_order', sa.String(length=10), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vibe_score_id'], ['vibe_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=100), nullable=False),
    sa.Column('signal_value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_extractions')
    op.drop_table('shap_explanations')
    op.drop_table('reviews')
    op.drop_table('dimension_scores')
    op.drop_table('vibe_scores')
    op.drop_table('social_metrics')
    op.drop_table('ingestion_jobs')
    op.drop_table('products')
    # ### end Alembic commands ###
