"""add_product_outcomes_and_ml_score

Revision ID: e1310708dead
Revises: 03369edf48f9
Create Date: 2026-05-12 11:28:58.196515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1310708dead'
down_revision: Union[str, None] = '03369edf48f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_outcomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('viral_proxy', sa.Boolean(), nullable=True),
    sa.Column('engagement_signal', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('label_method', sa.String(length=50), nullable=False),
    sa.Column('labeled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('n_reviews_used', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.add_column('vibe_scores', sa.Column('ml_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('vibe_scores', sa.Column('ml_model_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vibe_scores', 'ml_model_version')
    op.drop_column('vibe_scores', 'ml_score')
    op.drop_table('product_outcomes')
    # ### end Alembic commands ###
